version: '3.8'

services:

  # -----------------------------------------------------------------------------------
  # NOSQL DATABASE CONTAINER
  # -----------------------------------------------------------------------------------
  mongo:
    image: mongo
    volumes:
      - "mongodb:/data/db"
    ports:
      - "27017:27017"
    networks:
      - km-flask

  # -----------------------------------------------------------------------------------
  # RELATIONAL DATABASE CONTAINER
  # -----------------------------------------------------------------------------------
  mysql:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_1
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3307
    ports:
      - '3307:3307'
    expose:
      - 3307
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    networks:
      - km-flask


  # -----------------------------------------------------------------------------------
  # PARCEL LOCKERS WEB APP CONTAINER
  # -----------------------------------------------------------------------------------
  flask-parcel-lockers:
    image: adrianfr10/flask-parcel-lockers
    container_name: flask-parcel-lockers
    command: gunicorn --bind 0.0.0.0:8010 --workers 4 'main:create_app()' --reload
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8010:8010"
    networks:
      km-flask:
        aliases:
          - flask-parcel-lockers-app

  # -----------------------------------------------------------------------------------
  # CUSTOMERS WEB APP CONTAINER
  # -----------------------------------------------------------------------------------
  flask-customers:
    image: adrianfr10/flask-customers
    container_name: flask-customers
    command: gunicorn --bind 0.0.0.0:8011 --workers 4 'main:create_app()' --reload
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8011:8011"
    networks:
      km-flask:
        aliases:
          - flask-customers-app

  # -----------------------------------------------------------------------------------
  # CUSTOMERS WEB APP NGINX CONTAINER
  # -----------------------------------------------------------------------------------
  nginx-customers:
    image: nginx:latest
    volumes:
      - ./customers-app/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '81:81'
    depends_on:
      - flask-customers
    networks:
      - km-flask

  # -----------------------------------------------------------------------------------
  # PARCEL LOCKERS WEB APP NGINX CONTAINER
  # -----------------------------------------------------------------------------------
  nginx-parcel-lockers:
    image: nginx:latest
    volumes:
      - ./parcel-locker-app/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - flask-parcel-lockers
    networks:
      - km-flask

volumes:
  mysql:
  mongodb:

networks:
  km-flask: